---
title: "paul tsagaroulis - about me"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-61071-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-61071-2');
</script>

### Hello... My research interest is in developing a better understanding of how data visualization practices may help facilitate comprehension.  

#### My study explored the relationship data visualizations (tables and bar charts) and comprehension about the data. 

Abstract: Many organizations are “data rich, but insight poor” and contend with challenges developing data visualizations that facilitate insights. Studies show that numeracy, graph literacy, and cognitive processes influence how people perceive data visualizations. However, empirical studies on data visualization practices, numeracy, and graph literacy are rare. This study, which used a cognitive psychology framework, explains how data comprehension varies by data visualization practices and by measures of subjective numeracy (SNS) and subjective graph literacy (SGL). This paper presents findings from 212 participants (students and professionals) who viewed data visualizations from the U.S. Bureau of Labor Statistics. Participants were randomly assigned to one of four groups. Each group saw a table and a chart across two scenarios (the original table or chart, and modified versions using data visualization best practices). There were four key findings: 1) Overall, participants who saw tables had higher data comprehension than participants who saw charts, 2) participants who saw the best practice chart had higher data comprehension than participants who saw the control stacked bar chart, 3) participants with high SNS or high SGL had higher data comprehension (except for participants with high SGL in one scenario), and 4) data comprehension correlated positively with SNS and SGL. Implications for theory and practice expand the field of data visualization. A central principle is that the seeing and thinking of data can facilitate cognitive tasks. This study may help analysts develop a better understanding of how to communicate findings using data visualization best practices.

Tsagaroulis, P. (2020). Data visualization, numeracy and graph literacy: Seeing and thinking of data presented as tables or charts.
